name: M3U Listesini Senkronize Et

on:
  
  schedule:
    - cron: '0 */6 * * *'

 
  workflow_dispatch:


  sync-m3u-file:

    runs-on: ubuntu-latest

    steps:

      - name: Depoyu Checkout Et
        uses: actions/checkout@v4

      - name: Kaynak M3U Dosyasını İndir ve Güncelle
        run: |
          # Kaynak dosyanın URL'si
          SOURCE_URL="https://raw.githubusercontent.com/atakan1983/tvepic/refs/heads/main/mehmet_guncel.m3u"
          
          # Hedef dosyanın adı
          TARGET_FILE="gtv.m3u"
          
          # Kaynak dosyayı 'source.m3u' olarak indir
          curl -L -o source.m3u "$SOURCE_URL"
          
          # Eğer indirme başarılı olduysa devam et
          if [ $? -eq 0 ]; then
            echo "Kaynak dosya başarıyla indirildi."
            
            # Eğer hedef dosya (gtv.m3u) varsa ve içerikleri aynıysa bir şey yapma
            if [ -f "$TARGET_FILE" ] && cmp -s "$TARGET_FILE" "source.m3u"; then
              echo "Dosyalar zaten senkronize. Değişiklik yok."
            else
              echo "Değişiklik tespit edildi. Dosya güncelleniyor."
              # İndirilen yeni dosyayı hedef dosyanın üzerine yaz
              mv source.m3u "$TARGET_FILE"
            fi
          else
            echo "Kaynak dosya indirilemedi. İşlem iptal ediliyor."
            exit 1
          fi

      - name: Değişiklikleri Depoya Gönder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Otomatik Güncelleme: M3U listesi senkronize edildi"
          
          file_pattern: gtv.m3u

          branch: main
          
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
